apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-basic-1777032404070
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/quay_xjiang/test-image:github-5e5f2119137a2a759020829d20e9f2ffd1218522
        name: container-image  
